services:
  backend:
    image: zzun73/sogoo-be-main:main-latest
    container_name: sogoo-be-main
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sosang
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      CONFIG_USERNAME: ${CONFIG_USERNAME}
      CONFIG_PASSWORD: ${CONFIG_PASSWORD}
    depends_on:
      - postgres
      - elasticsearch
    networks:
      - sogoo-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:16.4
    container_name: sogoo-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sogoo-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms3g -Xmx3g
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins 
    networks:
      - sogoo-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: >
      bash -c "chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/plugins && 
      ./bin/elasticsearch-plugin install analysis-nori || exit 1; 
      /usr/local/bin/docker-entrypoint.sh"

networks:
  sogoo-network:
    driver: bridge

volumes:
  postgres-data:
  esdata:
